import type { Broadcast, VideoResult } from './types'

type Seed = {
  id: string
  title: string
  channelTitle: string
  handle: string
  publishedAt: string
  durationSec: number
  viewCount: number
  likeCount: number
  categoryId: string
  description: string
  definition?: 'hd' | 'sd'
  caption?: boolean
  license?: 'youtube' | 'creativeCommon'
  language?: string
  regionCode?: string
  live?: Broadcast
}

function video(seed: Seed): VideoResult {
  return {
    id: seed.id,
    title: seed.title,
    description: seed.description,
    channelTitle: seed.channelTitle,
    channelId: '',
    channelHandle: seed.handle,
    channelUrl: `https://www.youtube.com/@${seed.handle}`,
    publishedAt: seed.publishedAt,
    thumbnail: `https://i.ytimg.com/vi/${seed.id}/hqdefault.jpg`,
    durationSec: seed.durationSec,
    viewCount: seed.viewCount,
    likeCount: seed.likeCount,
    definition: seed.definition ?? 'hd',
    caption: seed.caption ?? true,
    license: seed.license ?? 'youtube',
    dimension: '2d',
    categoryId: seed.categoryId,
    language: seed.language ?? 'en',
    regionCode: seed.regionCode ?? 'US',
    liveBroadcastContent: seed.live ?? 'none',
    embeddable: true,
  }
}

export const CATALOG: VideoResult[] = [
  video({
    id: 'jNQXAC9IVRw',
    title: 'Me at the zoo',
    channelTitle: 'jawed',
    handle: 'jawed',
    publishedAt: '2005-04-23T20:27:00.000Z',
    durationSec: 19,
    viewCount: 340_000_000,
    likeCount: 18_000_000,
    categoryId: '23',
    definition: 'sd',
    caption: false,
    description: 'The first video uploaded to YouTube, filmed at the San Diego Zoo.',
  }),
  video({
    id: 'dQw4w9WgXcQ',
    title: 'Rick Astley - Never Gonna Give You Up (Official Video) (4K Remaster)',
    channelTitle: 'Rick Astley',
    handle: 'RickAstleyYT',
    publishedAt: '2009-10-25T00:00:00.000Z',
    durationSec: 213,
    viewCount: 1_600_000_000,
    likeCount: 18_000_000,
    categoryId: '10',
    regionCode: 'GB',
    description: 'Official music video, remastered in 4K.',
  }),
  video({
    id: '9bZkp7q19f0',
    title: 'PSY - GANGNAM STYLE(강남스타일) M/V',
    channelTitle: 'officialpsy',
    handle: 'officialpsy',
    publishedAt: '2012-07-15T00:00:00.000Z',
    durationSec: 252,
    viewCount: 5_100_000_000,
    likeCount: 28_000_000,
    categoryId: '10',
    language: 'ko',
    regionCode: 'KR',
    description: 'Official music video filmed in Seoul.',
  }),
  video({
    id: 'kJQP7kiw5Fk',
    title: 'Luis Fonsi - Despacito ft. Daddy Yankee',
    channelTitle: 'LuisFonsiVEVO',
    handle: 'LuisFonsiVEVO',
    publishedAt: '2017-01-12T00:00:00.000Z',
    durationSec: 282,
    viewCount: 8_200_000_000,
    likeCount: 40_000_000,
    categoryId: '10',
    language: 'es',
    description: 'Official music video.',
  }),
  video({
    id: 'fJ9rUzIMcZQ',
    title: 'Queen – Bohemian Rhapsody (Official Video Remastered)',
    channelTitle: 'Queen Official',
    handle: 'Queen',
    publishedAt: '2008-08-01T00:00:00.000Z',
    durationSec: 355,
    viewCount: 2_100_000_000,
    likeCount: 20_000_000,
    categoryId: '10',
    regionCode: 'GB',
    description: 'Official remastered music video.',
  }),
  video({
    id: 'JGwWNGJdvx8',
    title: 'Ed Sheeran - Shape of You (Official Music Video)',
    channelTitle: 'Ed Sheeran',
    handle: 'EdSheeran',
    publishedAt: '2017-01-30T00:00:00.000Z',
    durationSec: 263,
    viewCount: 6_100_000_000,
    likeCount: 32_000_000,
    categoryId: '10',
    regionCode: 'GB',
    description: 'Official music video.',
  }),
  video({
    id: 'OPf0YbXqDm0',
    title: 'Mark Ronson - Uptown Funk (Official Video) ft. Bruno Mars',
    channelTitle: 'MarkRonsonVEVO',
    handle: 'MarkRonsonVEVO',
    publishedAt: '2014-11-19T00:00:00.000Z',
    durationSec: 270,
    viewCount: 5_200_000_000,
    likeCount: 24_000_000,
    categoryId: '10',
    regionCode: 'GB',
    description: 'Official music video.',
  }),
  video({
    id: 'hTWKbfoikeg',
    title: 'Nirvana - Smells Like Teen Spirit (Official Music Video)',
    channelTitle: 'NirvanaVEVO',
    handle: 'NirvanaVEVO',
    publishedAt: '2009-06-16T00:00:00.000Z',
    durationSec: 278,
    viewCount: 1_900_000_000,
    likeCount: 16_000_000,
    categoryId: '10',
    description: 'Official music video.',
  }),
  video({
    id: 'YQHsXMglC9A',
    title: 'Adele - Hello (Official Music Video)',
    channelTitle: 'Adele',
    handle: 'adele',
    publishedAt: '2015-10-22T00:00:00.000Z',
    durationSec: 367,
    viewCount: 3_400_000_000,
    likeCount: 22_000_000,
    categoryId: '10',
    regionCode: 'GB',
    description: 'Official music video.',
  }),
  video({
    id: '60ItHLz5WEA',
    title: 'Alan Walker - Faded',
    channelTitle: 'Alan Walker',
    handle: 'Alanwalkermusic',
    publishedAt: '2015-12-03T00:00:00.000Z',
    durationSec: 212,
    viewCount: 3_500_000_000,
    likeCount: 20_000_000,
    categoryId: '10',
    regionCode: 'NO',
    description: 'Official music video.',
  }),
  video({
    id: 'e-ORhEE9VVg',
    title: 'Taylor Swift - Blank Space',
    channelTitle: 'Taylor Swift',
    handle: 'TaylorSwift',
    publishedAt: '2014-11-10T00:00:00.000Z',
    durationSec: 273,
    viewCount: 3_300_000_000,
    likeCount: 18_000_000,
    categoryId: '10',
    description: 'Official music video.',
  }),
  video({
    id: '09R8_2nJtjg',
    title: 'Maroon 5 - Sugar (Official Music Video)',
    channelTitle: 'Maroon5VEVO',
    handle: 'Maroon5VEVO',
    publishedAt: '2015-01-14T00:00:00.000Z',
    durationSec: 303,
    viewCount: 3_900_000_000,
    likeCount: 18_000_000,
    categoryId: '10',
    description: 'Official music video.',
  }),
  video({
    id: 'CevxZvSJLk8',
    title: 'Katy Perry - Roar',
    channelTitle: 'KatyPerryVEVO',
    handle: 'KatyPerryVEVO',
    publishedAt: '2013-09-05T00:00:00.000Z',
    durationSec: 271,
    viewCount: 3_800_000_000,
    likeCount: 17_000_000,
    categoryId: '10',
    description: 'Official music video.',
  }),
  video({
    id: 'pRpeEdMmmQ0',
    title: 'Shakira - Waka Waka (This Time for Africa) (The Official 2010 FIFA World Cup™ Song)',
    channelTitle: 'shakiraVEVO',
    handle: 'shakiraVEVO',
    publishedAt: '2010-06-04T00:00:00.000Z',
    durationSec: 211,
    viewCount: 3_700_000_000,
    likeCount: 16_000_000,
    categoryId: '10',
    language: 'es',
    regionCode: 'CO',
    description: 'Official 2010 FIFA World Cup song.',
  }),
  video({
    id: 'RgKAFK5djSk',
    title: 'Wiz Khalifa - See You Again ft. Charlie Puth [Official Video] Furious 7 Soundtrack',
    channelTitle: 'Wiz Khalifa Music',
    handle: 'wizkhalifamusic9871',
    publishedAt: '2015-04-06T00:00:00.000Z',
    durationSec: 237,
    viewCount: 6_000_000_000,
    likeCount: 30_000_000,
    categoryId: '10',
    description: 'Official soundtrack music video.',
  }),
  video({
    id: 'nfWlot6h_JM',
    title: 'Taylor Swift - Shake It Off',
    channelTitle: 'Taylor Swift',
    handle: 'TaylorSwift',
    publishedAt: '2014-08-18T00:00:00.000Z',
    durationSec: 252,
    viewCount: 3_200_000_000,
    likeCount: 16_000_000,
    categoryId: '10',
    description: 'Official music video.',
  }),
  video({
    id: 'kXYiU_JCYtU',
    title: 'Numb (Official Music Video) [4K UPGRADE] – Linkin Park',
    channelTitle: 'Linkin Park',
    handle: 'LinkinPark',
    publishedAt: '2007-03-05T00:00:00.000Z',
    durationSec: 186,
    viewCount: 2_200_000_000,
    likeCount: 15_000_000,
    categoryId: '10',
    description: 'Official music video upgraded to 4K.',
  }),
  video({
    id: '2Vv-BfVoq4g',
    title: 'Ed Sheeran - Perfect (Official Music Video)',
    channelTitle: 'Ed Sheeran',
    handle: 'EdSheeran',
    publishedAt: '2017-11-09T00:00:00.000Z',
    durationSec: 280,
    viewCount: 3_700_000_000,
    likeCount: 20_000_000,
    categoryId: '10',
    regionCode: 'GB',
    description: 'Official music video.',
  }),
  video({
    id: 'jofNR_WkoCE',
    title: 'Ylvis - The Fox (What Does The Fox Say?) [Official music video HD]',
    channelTitle: 'TVNorge',
    handle: 'tvnorge',
    publishedAt: '2013-09-03T00:00:00.000Z',
    durationSec: 225,
    viewCount: 1_100_000_000,
    likeCount: 8_000_000,
    categoryId: '10',
    regionCode: 'NO',
    description: 'Official music video.',
  }),
  video({
    id: 'aqz-KE-bpKQ',
    title: 'Big Buck Bunny 60fps 4K - Official Blender Foundation Short Film',
    channelTitle: 'Blender',
    handle: 'BlenderOfficial',
    publishedAt: '2014-10-10T00:00:00.000Z',
    durationSec: 635,
    viewCount: 18_000_000,
    likeCount: 400_000,
    categoryId: '1',
    license: 'creativeCommon',
    regionCode: 'NL',
    description: 'Open movie short film from the Blender Foundation, released under Creative Commons, in 4K.',
  }),
  video({
    id: 'YE7VzlLtp-4',
    title: 'Big Buck Bunny',
    channelTitle: 'Blender',
    handle: 'BlenderOfficial',
    publishedAt: '2008-05-20T00:00:00.000Z',
    durationSec: 596,
    viewCount: 22_000_000,
    likeCount: 350_000,
    categoryId: '1',
    license: 'creativeCommon',
    regionCode: 'NL',
    description: 'Original Blender Foundation open movie, Creative Commons.',
  }),
  video({
    id: 'eRsGyueVLvQ',
    title: 'Sintel - Open Movie by Blender Foundation',
    channelTitle: 'Blender',
    handle: 'BlenderOfficial',
    publishedAt: '2010-09-30T00:00:00.000Z',
    durationSec: 888,
    viewCount: 12_000_000,
    likeCount: 220_000,
    categoryId: '1',
    license: 'creativeCommon',
    regionCode: 'NL',
    description: 'Fantasy open movie short film, Creative Commons.',
  }),
  video({
    id: 'R6MlUcmOul8',
    title: 'Tears of Steel - Blender VFX Open Movie',
    channelTitle: 'Blender',
    handle: 'BlenderOfficial',
    publishedAt: '2012-09-26T00:00:00.000Z',
    durationSec: 734,
    viewCount: 8_000_000,
    likeCount: 140_000,
    categoryId: '1',
    license: 'creativeCommon',
    regionCode: 'NL',
    description: 'Science fiction visual-effects open movie, Creative Commons.',
  }),
  video({
    id: 'iG9CE55wbtY',
    title: 'Do schools kill creativity? | Sir Ken Robinson | TED',
    channelTitle: 'TED',
    handle: 'TED',
    publishedAt: '2007-01-06T00:00:00.000Z',
    durationSec: 1164,
    viewCount: 75_000_000,
    likeCount: 1_400_000,
    categoryId: '27',
    description: 'TED talk on creativity and education.',
  }),
  video({
    id: '6Af6b_wyiwI',
    title: 'The next outbreak? We’re not ready | Bill Gates | TED',
    channelTitle: 'TED',
    handle: 'TED',
    publishedAt: '2015-04-03T00:00:00.000Z',
    durationSec: 504,
    viewCount: 28_000_000,
    likeCount: 500_000,
    categoryId: '27',
    description: 'TED talk about preparing for the next epidemic.',
  }),
  video({
    id: 'rfscVS0vtbw',
    title: 'Learn Python - Full Course for Beginners [Tutorial]',
    channelTitle: 'freeCodeCamp.org',
    handle: 'freecodecamp',
    publishedAt: '2018-08-15T00:00:00.000Z',
    durationSec: 16012,
    viewCount: 45_000_000,
    likeCount: 900_000,
    categoryId: '27',
    description: 'Beginner programming tutorial and full Python course.',
  }),
  video({
    id: 'PkZNo7MFNFg',
    title: 'Learn JavaScript - Full Course for Beginners',
    channelTitle: 'freeCodeCamp.org',
    handle: 'freecodecamp',
    publishedAt: '2018-12-10T00:00:00.000Z',
    durationSec: 12360,
    viewCount: 20_000_000,
    likeCount: 400_000,
    categoryId: '27',
    description: 'Beginner programming tutorial and full JavaScript course.',
  }),
  video({
    id: 'fNk_zzaMoSs',
    title: 'Vectors | Chapter 1, Essence of linear algebra',
    channelTitle: '3Blue1Brown',
    handle: '3blue1brown',
    publishedAt: '2016-08-06T00:00:00.000Z',
    durationSec: 590,
    viewCount: 18_000_000,
    likeCount: 500_000,
    categoryId: '27',
    description: 'Animated math lesson on vectors.',
  }),
  video({
    id: 'kjBOesZCoqc',
    title: 'Essence of linear algebra preview',
    channelTitle: '3Blue1Brown',
    handle: '3blue1brown',
    publishedAt: '2016-08-01T00:00:00.000Z',
    durationSec: 309,
    viewCount: 5_000_000,
    likeCount: 120_000,
    categoryId: '27',
    description: 'Preview of an animated linear algebra series.',
  }),
  video({
    id: 'WUvTyaaNkzM',
    title: 'The essence of calculus',
    channelTitle: '3Blue1Brown',
    handle: '3blue1brown',
    publishedAt: '2017-04-28T00:00:00.000Z',
    durationSec: 1020,
    viewCount: 12_000_000,
    likeCount: 380_000,
    categoryId: '27',
    description: 'Animated introduction to calculus.',
  }),
  video({
    id: 'zQGOcOUBi6s',
    title: 'The Immune System Explained I – Bacteria Infection',
    channelTitle: 'Kurzgesagt – In a Nutshell',
    handle: 'kurzgesagt',
    publishedAt: '2014-11-27T00:00:00.000Z',
    durationSec: 408,
    viewCount: 42_000_000,
    likeCount: 900_000,
    categoryId: '28',
    regionCode: 'DE',
    description: 'Animated science explainer about the immune system.',
  }),
  video({
    id: 'txmKr69jGBk',
    title: 'Levitating Barbecue! Electromagnetic Induction',
    channelTitle: 'Veritasium',
    handle: 'veritasium',
    publishedAt: '2018-07-20T00:00:00.000Z',
    durationSec: 420,
    viewCount: 25_000_000,
    likeCount: 700_000,
    categoryId: '28',
    description: 'Science demonstration of electromagnetic induction.',
  }),
  video({
    id: 'HyWYpM_S-2c',
    title: 'React for the Haters in 100 Seconds',
    channelTitle: 'Fireship',
    handle: 'Fireship',
    publishedAt: '2023-05-01T00:00:00.000Z',
    durationSec: 145,
    viewCount: 2_000_000,
    likeCount: 200_000,
    categoryId: '28',
    description: 'A short technology explainer about React.',
  }),
  video({
    id: 'M7lc1UVf-VE',
    title: 'YouTube Developers Live: Embedded Web Player Customization',
    channelTitle: 'Google for Developers',
    handle: 'GoogleDevelopers',
    publishedAt: '2012-09-12T00:00:00.000Z',
    durationSec: 1500,
    viewCount: 1_200_000,
    likeCount: 18_000,
    categoryId: '28',
    live: 'completed',
    description: 'A completed live session about the embedded YouTube player.',
  }),
  video({
    id: 'bHQqvYy5KYo',
    title: "Google I/O 2011: YouTube's iframe Player: The Future of Embedding",
    channelTitle: 'Google for Developers',
    handle: 'GoogleDevelopers',
    publishedAt: '2011-05-10T00:00:00.000Z',
    durationSec: 2880,
    viewCount: 480_000,
    likeCount: 8_000,
    categoryId: '28',
    description: 'Conference talk about embedding the YouTube player.',
  }),
  video({
    id: 'MmB9b5njVbA',
    title: 'Official Minecraft Trailer',
    channelTitle: 'Minecraft',
    handle: 'minecraft',
    publishedAt: '2011-12-19T00:00:00.000Z',
    durationSec: 102,
    viewCount: 48_000_000,
    likeCount: 900_000,
    categoryId: '20',
    caption: false,
    description: 'Official game trailer.',
  }),
  video({
    id: 'LXb3EKWsInQ',
    title: 'COSTA RICA IN 4K 60fps HDR (ULTRA HD)',
    channelTitle: 'Jacob + Katie Schwarz',
    handle: 'JacobKatieSchwarz',
    publishedAt: '2018-06-01T00:00:00.000Z',
    durationSec: 512,
    viewCount: 40_000_000,
    likeCount: 600_000,
    categoryId: '19',
    caption: false,
    description: 'Nature and travel scenery filmed in 4K.',
  }),
  video({
    id: '1La4QzGeaaQ',
    title: 'Peru 8K HDR 60FPS (FUHD)',
    channelTitle: 'Jacob + Katie Schwarz',
    handle: 'JacobKatieSchwarz',
    publishedAt: '2024-11-02T00:00:00.000Z',
    durationSec: 480,
    viewCount: 12_000_000,
    likeCount: 180_000,
    categoryId: '19',
    caption: false,
    description: 'Nature and travel scenery filmed in 8K.',
  }),
  video({
    id: 'ZXsQAXx_ao0',
    title: 'Shia LaBeouf "Just Do It" Motivational Speech (Original Video by LaBeouf, Rönkkö & Turner)',
    channelTitle: 'MotivaShian',
    handle: 'motivashian4248',
    publishedAt: '2015-06-01T00:00:00.000Z',
    durationSec: 90,
    viewCount: 40_000_000,
    likeCount: 700_000,
    categoryId: '23',
    caption: false,
    description: 'Short motivational comedy clip.',
  }),
  video({
    id: '5qap5aO4i9A',
    title: 'lofi hip hop radio - beats to relax/study to',
    channelTitle: 'Lofi Girl',
    handle: 'LofiGirl',
    publishedAt: '2020-02-22T00:00:00.000Z',
    durationSec: 0,
    viewCount: 200_000_000,
    likeCount: 3_000_000,
    categoryId: '24',
    caption: false,
    regionCode: 'FR',
    live: 'live',
    description: 'A long-running live radio stream of beats to study to.',
  }),
]
